In [1]:
# Exp no: 3

In [2]:
# Name : Srushti Gajanan Tade
# Roll no : 62
# SEC :B 
#Subject: ET1
#data :

In [3]:
# Basic of Data frame

# Creating a series

In [4]:
# importing the basic library

In [16]:
import pandas as pd

In [17]:
# creating student Name list

In [21]:
Name =["srushti " , "Ashvini","janhavi","yash ","shlok"]

In [22]:
Name

['srushti ', 'Ashvini', 'janhavi', 'yash ', 'shlok']

In [23]:
Rolllist=pd.Series(Name,index=[1,2,3,4,5])

In [24]:
print(Rolllist)

1    srushti
2     Ashvini
3     janhavi
4       yash
5       shlok
dtype: object

# Creating a Data Frame

In [30]:
df=pd.DataFrame([[10,11,12,13],[14,15,16,17],[15,17,18,12],[20,27,26,13]],columns=["CD","DBMS","DSS","CAO"])

In [31]:
df

   CD  DBMS  DSS  CAO
0  10    11   12   13
1  14    15   16   17
2  15    17   18   12
3  20    27   26   13

In [32]:
df.shape

(4, 4)

In [33]:
df.size

16

In [34]:
df.ndim

2

In [38]:
df2=pd.DataFrame([[9,12,10,11]],columns=["CD","DBMS","DSS","CAO"])

In [39]:
df3=pd.concat([df,df2],ignore_index=True)

In [40]:
df3

   CD  DBMS  DSS  CAO
0  10    11   12   13
1  14    15   16   17
2  15    17   18   12
3  20    27   26   13
4   9    12   10   11

In [41]:
df3["DM"]=[11,12,13,14,15]

In [42]:
df3

   CD  DBMS  DSS  CAO  DM
0  10    11   12   13  11
1  14    15   16   17  12
2  15    17   18   12  13
3  20    27   26   13  14
4   9    12   10   11  15

# Deleting Record(Row)Form Date Frame

In [43]:
df4=df3.drop(index=[1])

In [44]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    11   12   13  11
2  15    17   18   12  13
3  20    27   26   13  14
4   9    12   10   11  15

In [45]:
print("Mean of DSS :",df4["DSS"].median())

Mean of DSS : 15.0

In [47]:
print("Mean of DSS :",df4["DSS"].mode())

Mean of DSS : 0    10
1    12
2    18
3    26
Name: DSS, dtype: int64

In [48]:
print("Mean of DSS :",df4["DSS"].mode())

Mean of DSS : 0    10
1    12
2    18
3    26
Name: DSS, dtype: int64

In [49]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    11   12   13  11
2  15    17   18   12  13
3  20    27   26   13  14
4   9    12   10   11  15